import type { Metadata } from "next";
import "./globals.css";
import { Oswald } from "next/font/google";
import Header from "@/components/layout/Header";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Bangladesh Athletics Federation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.className}antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
